### ISSUE TITLE
Adventure 003 retrospective

### ISSUE THREAD

**Issue by patmaddox** [RubySteps/21-day-challenge#1051]
Adventure 003 is over

**Comment by adeluccar** [comment]
Awesome! Let the games begin! 

I will use this month's adventure to start a long running project. A rails app designed to show off an art collection and sell art pieces. I intend to learn the basic ropes (your typical mvc app) plus how to serve assets from amazon's s3's service. If time allows, I will also explore adding the polymer paper framework instead of your usual bootstrap or foundation one.

**Comment by patmaddox** [comment]
well that was a quiet one :)
